spring.application.name=App

# server port
server.port=8090

# database - h2 - file
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:file:~/bilgeadam_2026_spring;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=sa

# jpa config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true